# Generated by Django 5.0.3 on 2024-04-02 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentorg', '0002_orgmember_organization'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orgmember',
            old_name='Organization',
            new_name='organization',
        ),
    ]
